### ISSUE TITLE
After the upgrade to 2021.12.2 the entity is not available

### ISSUE THREAD

**Issue by damiano75** [custom-components/camera.combined#16]
**Version of the custom_component**

0.2.1

**Describe the bug**

![image](https://user-images.githubusercontent.com/47896789/146902147-76dec48f-311d-428a-869c-2ffcb55d00cd.png)

**log**

```
2021-12-19 15:15:12 ERROR (MainThread) [homeassistant.components.camera] Error while setting up combined platform for camera
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/combined/camera.py", line 38, in setup_platform
camera = CombinedhCamera(hass, name, entities, base_address)
File "/config/custom_components/combined/camera.py", line 49, in __init__
self.is_streaming = False
AttributeError: can't set attribute
```

**Comment by MrUkleja** [comment]
Not sure when this started, but I'm getting same error
